services:
    backend:
        build:
            context: .
            dockerfile: src/backend/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./src/backend:/app
        restart: unless-stopped

    frontend:
        build:
            context: .
            dockerfile: src/frontend/Dockerfile
            args:
                VITE_API_URL: /api/
        ports:
            - "8080:80"
        volumes:
            - ./src/frontend:/app
        restart: unless-stopped
        depends_on:
            - backend
