@startuml domain_model

skinparam nodesep 100
skinparam Ranksep 60

' Klassen
class Turnier {
  Name
  Datum
  Anzahl_Felder
}

class Leistungsgruppe {
  Name

}

class Spiel {
  Uhrzeit
  Punkte_Home
  Punkte_Away
  Feldnummmer
}

class Team {
  Name
}

class Turnierplan {
  QR-Code
  Anzahl_Runden
}

Turnier "3..*" -right- "1..*" Leistungsgruppe
Turnier "1"    -down--  "1" Turnierplan
Team    "1..*" -up- "1" Leistungsgruppe
Team    "1" -down-- "1..*" Spiel : Schiedsrichter >
Team    "1" -down- "*" Spiel : Team_Home >
Team    "1" -down- "*" Spiel : Team_Away >
Spiel   "3..*" -left- "1" Turnierplan

@enduml