@startuml domain_model

skinparam nodesep 100
skinparam Ranksep 60

' Klassen
class Turnier {
  Name
  Datum
  Anzahl_Felder
  QR-Code
  Anzahl_Runden
  Matchpoint
}

class Leistungsgruppe {
  Name

}

class Spiel {
  Uhrzeit
  Punkte_Home
  Punkte_Away
  Feldnummmer
}

class Team {
  Name
}



Turnier "1" -right- "1..2" Leistungsgruppe
Team    "3..12" -- "1" Leistungsgruppe
Team    "1" -left- "1..*" Spiel : Schiedsrichter >
Team    "1" -- "*" Spiel : Team_Home >
Team    "1" -- "*" Spiel : Team_Away >
Spiel   "3..*" -- "1" Turnier

@enduml
